package ffm.slc.model.enums;

/**
 * The item(s) denoting language(s) spoken or written.
 */
public enum LanguageItemType {
	SPANISH("Spanish"),
	VIETNAMESE("Vietnamese"),
	LAOTIAN_LAO_("Laotian (Lao)"),
	CAMBODIAN_KHMER_("Cambodian (Khmer)"),
	KOREAN("Korean"),
	JAPANESE("Japanese"),
	FRENCH("French"),
	GERMAN("German"),
	ENGLISH("English"),
	OTHER_LANGUAGES("Other languages"),
	AFRIKAANS_TAAL_("Afrikaans (Taal)"),
	AKAN_FANTE_ASANTE_("Akan (Fante, Asante)"),
	ALBANIAN_GHEG_KOSSOVO_MACEDONIA_("Albanian, Gheg (Kossovo/Macedonia)"),
	ALBANIAN_TOSK_ALBANIA_("Albanian, Tosk (Albania)"),
	ALGONQUIN("Algonquin"),
	AMHARIC("Amharic"),
	APACHE("Apache"),
	ARABIC("Arabic"),
	ARMENIAN("Armenian"),
	ASSYRIAN_SYRIAC_ARAMAIC_("Assyrian (Syriac, Aramaic)"),
	BALINESE("Balinese"),
	BENGALI("Bengali"),
	BOSNIAN("Bosnian"),
	BULGARIAN("Bulgarian"),
	BURMESE("Burmese"),
	CANTONESE_CHINESE_("Cantonese (Chinese)"),
	CEBUANO_VISAYAN_("Cebuano (Visayan)"),
	CHAMORRO("Chamorro"),
	CHAOCHOW_TEOCHIU_CHINESE_("Chaochow/Teochiu (Chinese)"),
	CHEROKEE("Cherokee"),
	CHIPPEWA_OJIBAWA_OTTAWA("Chippewa/Ojibawa/Ottawa"),
	CHOCTAW("Choctaw"),
	COMANCHE("Comanche"),
	COUSHATTA("Coushatta"),
	CREEK("Creek"),
	CROATIAN("Croatian"),
	CROW("Crow"),
	CZECH("Czech"),
	DANISH("Danish"),
	DARD("Dard"),
	DUTCH_FLEMISH("Dutch/Flemish"),
	EFIK("Efik"),
	ESKIMO("Eskimo"),
	ESTONIAN("Estonian"),
	ETHIOPIC("Ethiopic"),
	EWE("Ewe"),
	FARSI_PERSIAN_("Farsi (Persian)"),
	FINNISH("Finnish"),
	FUKIEN_HOKKIEN_CHINESE_("Fukien/Hokkien (Chinese)"),
	GAELIC_IRISH_("Gaelic (Irish)"),
	GAELIC_SCOTTISH_("Gaelic (Scottish)"),
	GREEK("Greek"),
	GUJARATI("Gujarati"),
	GUYANESE("Guyanese"),
	HAINANESE_CHINESE_("Hainanese (Chinese)"),
	HAITIAN_CREOLE("Haitian-Creole"),
	HAKKA_CHINESE_("Hakka (Chinese)"),
	HAUSA("Hausa"),
	HEBREW("Hebrew"),
	HINDI("Hindi"),
	HMONG("Hmong"),
	HOPI("Hopi"),
	HUNGARIAN("Hungarian"),
	IBO_IGBO("Ibo/Igbo"),
	ICELANDIC("Icelandic"),
	ILONGGO_HILIGAYNON_("Ilonggo (Hiligaynon)"),
	INDONESIAN("Indonesian"),
	ITALIAN("Italian"),
	KACHE_KAJE_JJU_("Kache (Kaje, Jju)"),
	KANNADA_KANARESE_("Kannada (Kanarese)"),
	KANURI("Kanuri"),
	KASHMIRI("Kashmiri"),
	KICKAPOO("Kickapoo"),
	KONKANI("Konkani"),
	KPELLE("Kpelle"),
	KRIO("Krio"),
	KURDISH("Kurdish"),
	KWA("Kwa"),
	LATVIAN("Latvian"),
	LINGALA("Lingala"),
	LITHUANIAN("Lithuanian"),
	LUGANDA("Luganda"),
	LUNDA("Lunda"),
	LUYIA_LUHYA_("Luyia (Luhya)"),
	MACEDONIAN("Macedonian"),
	MALAY("Malay"),
	MALAYALAM("Malayalam"),
	MALTESE("Maltese"),
	MANDARIN_CHINESE_("Mandarin (Chinese)"),
	MANDE("Mande"),
	MARATHI("Marathi"),
	MENOMINEE("Menominee"),
	MIEN_YAO_("Mien (Yao)"),
	NAVAJO("Navajo"),
	NEPALI("Nepali"),
	NORWEGIAN("Norwegian"),
	OKINAWAN("Okinawan"),
	ONEIDA("Oneida"),
	ORIYA("Oriya"),
	ORRI_ORING_("Orri (Oring)"),
	PAMPANGAN("Pampangan"),
	PANJABI_PUNJABI_("Panjabi (Punjabi)"),
	PASHTO_PUSHTO_("Pashto (Pushto)"),
	PILIPINO_TAGALOG_("Pilipino (Tagalog)"),
	PIMA("Pima"),
	POLISH("Polish"),
	PORTUGUESE("Portuguese"),
	PUEBLO("Pueblo"),
	ROMANIAN("Romanian"),
	ROMANY_GYPSY_("Romany (Gypsy)"),
	RUSSIAN("Russian"),
	SAMOAN("Samoan"),
	SERBIAN("Serbian"),
	SHANGHAI_CHINESE_("Shanghai (Chinese)"),
	SHONA("Shona"),
	SIKKIMESE("Sikkimese"),
	SINDHI("Sindhi"),
	SINHALESE_SRI_LANKA_("Sinhalese (Sri Lanka)"),
	SIOUX_DAKOTA_("Sioux (Dakota)"),
	SLAVIC("Slavic"),
	SLOVENIAN_SLOVENE_("Slovenian (Slovene)"),
	SOMALI("Somali"),
	SOTHO("Sotho"),
	SWAHILI("Swahili"),
	SWEDISH("Swedish"),
	TAIWANESE_FORMOSAN_MIN_NAN_CHINESE_("Taiwanese/Formosan/Min Nan (Chinese)"),
	TAMIL("Tamil"),
	TELUGU_TELEGU_("Telugu (Telegu)"),
	THAI("Thai"),
	TIBETAN("Tibetan"),
	TIGRINYA("Tigrinya"),
	TIWA("Tiwa"),
	TULUAU("Tuluau"),
	TURKISH("Turkish"),
	UKRAINIAN("Ukrainian"),
	URDU("Urdu"),
	WELSH("Welsh"),
	WINNEBAGO("Winnebago"),
	YIDDISH("Yiddish"),
	YOMBE("Yombe"),
	YORUBA("Yoruba");

	private String prettyName;

	LanguageItemType(String prettyName) {
		this.prettyName = prettyName;
	}

	@Override
	public String toString() {
		return prettyName;
	}
}
